// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQLj-JX-b-z5JMYYhRzFRilgCxrp-MBgA',
    appId: '1:860615079429:web:5876da0c5fdf4d04238e6c',
    messagingSenderId: '860615079429',
    projectId: 'dashboard-aa18d',
    authDomain: 'dashboard-aa18d.firebaseapp.com',
    storageBucket: 'dashboard-aa18d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHdIZjWBLW21ytUdkFZ3HlJv5Tr0Wj58c',
    appId: '1:860615079429:android:c11e306aeeacb3ac238e6c',
    messagingSenderId: '860615079429',
    projectId: 'dashboard-aa18d',
    storageBucket: 'dashboard-aa18d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRrbf3ItuHEyEzb4iB9nJUAnI2JEj-Yfc',
    appId: '1:860615079429:ios:01fefc686ceaca65238e6c',
    messagingSenderId: '860615079429',
    projectId: 'dashboard-aa18d',
    storageBucket: 'dashboard-aa18d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRrbf3ItuHEyEzb4iB9nJUAnI2JEj-Yfc',
    appId: '1:860615079429:ios:01fefc686ceaca65238e6c',
    messagingSenderId: '860615079429',
    projectId: 'dashboard-aa18d',
    storageBucket: 'dashboard-aa18d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQLj-JX-b-z5JMYYhRzFRilgCxrp-MBgA',
    appId: '1:860615079429:web:87aff79b30e7db90238e6c',
    messagingSenderId: '860615079429',
    projectId: 'dashboard-aa18d',
    authDomain: 'dashboard-aa18d.firebaseapp.com',
    storageBucket: 'dashboard-aa18d.firebasestorage.app',
  );
}
